// ─────────────────────────────────────────────────────────────
// WeekPilot — Markdown File Output
// ─────────────────────────────────────────────────────────────

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { GeneratedSummary, WeekPilotConfig } from '../types.js';
import { weekNumber } from '../utils/dates.js';
import { logger } from '../utils/logger.js';
import { ensureDir } from '../config.js';

/**
 * Save a generated summary as a markdown file.
 *
 * Daily summaries:  ~/.weekpilot/outputs/daily/2026-05-25.md
 * Weekly summaries: ~/.weekpilot/outputs/weekly/2026-W21.md
 */
export function saveSummaryToFile(
  config: WeekPilotConfig,
  summary: GeneratedSummary
): string {
  const subdir = summary.type === 'daily' ? 'daily' : 'weekly';
  const dir = path.join(config.outputsDir, subdir);
  ensureDir(dir);

  // Determine filename
  let filename: string;
  if (summary.type === 'daily') {
    filename = `${summary.date}.md`;
  } else {
    // Use ISO week format for weekly summaries
    const week = weekNumber(new Date(summary.date + 'T00:00:00'));
    filename = `${week}.md`;
  }

  const filepath = path.join(dir, filename);

  // Build markdown content with frontmatter
  const content = buildMarkdown(summary);
  fs.writeFileSync(filepath, content, 'utf-8');

  logger.success(`Saved ${summary.type} summary to ${filepath}`);
  return filepath;
}

/**
 * Build a clean markdown document from a summary.
 */
function buildMarkdown(summary: GeneratedSummary): string {
  const typeLabel =
    summary.type === 'daily' ? 'Daily Standup' : 'Weekly Summary';

  const parts: string[] = [
    '---',
    `type: ${summary.type}`,
    `date: ${summary.date}`,
    `generated: ${summary.createdAt}`,
    `generator: weekpilot`,
    '---',
    '',
    `# ${typeLabel} — ${summary.date}`,
    '',
    summary.content,
    '',
    '---',
    `*Generated by WeekPilot at ${new Date(summary.createdAt).toLocaleString()}*`,
    '',
  ];

  return parts.join('\n');
}

/**
 * List all saved summary files of a given type.
 */
export function listSavedSummaries(
  config: WeekPilotConfig,
  type: 'daily' | 'weekly'
): string[] {
  const dir = path.join(config.outputsDir, type);

  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse();
}

// TODO(phase-2): Add weekly Excel export using a library like exceljs
// TODO(phase-2): Add HTML output format for email sharing
